---
abstract: 'File::Slurp::Affix opens a file and creates an array with an optional prefix, suffix, or both with an optional separator in your preferred encoding.'
author:
  - 'Lady Aleena <aleena@cpan.org>'
build_requires:
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Slurp-Affix
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '0'
  perl: '5.006'
version: 0.01_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
